language: node_js
node_js:
  - 12
instal:
  - npm install
  - npm run join
script:
  - npm run build
branches:
  only:
    - master
    - dev
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  verbose: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  on:
    branch: dev

